export { default as Home } from './Home'
export { default as About } from './About'
export { default as Detail } from './Detail'
export { default as Topic } from './Topic'
export { default as Dashboard } from './Dashboard'
